language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: a92b9866ebb6f342445ccfc5c816f3ad72e6c0aa9de55041ae475d0f8c9222c8
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: fLTqCKmboGQ3+OfIzNW12+xZl0MYChHmRrE3vDGqMkqjChYIKEwp0AN1QQK7OkxUa8lXZAZSaRNUtfJZrhZy5LfMvxONpzSGY3DPAKgnWjDEC0Jf+uKHPI2IhDcUkyHjMQQBKLOhLhtvu4C2kX6Q4eiOjdc19Bcs2ZpplJf6HkT5vGSXmKSbSkZoX8/AXVowV25TanTbMCD3XIwHFeL7ZN0bHupqgSnuAh1MdAeyklweBr6YvCd3qfYKXVhCR3mWQ7ZNVBlZG60MK7M5pkeLjaSPIQCyzldC5U9R3OGUX+babA8BlrPeeXHtpKURElX3luqOT7CwBxgasra7dGr1OAvZScEiHlLzC9J9CWcM03cFeTAc+41tqhFIVdhqrqxoGYIPuX9EtHGQ/AVMw2Z8Dx1jlAfiWZmOMbzfvIKOjrfNhm6I6xpRVDlqJtdnOvw67f9Mo4xE1VJ+alebdZQBY+WnMJN4uHHa3udglD9OGGuAQQRAKDpndJWDpf3gr/7ye3fdvymgW7hKGrB5BObOK1J1JpAY1cLsMXZiGSPb8fJgeJm6r0eRDi3oKmUarhR7VexCOvIhMpNtA2LBI8gzkM4GOKCSWdZ4pPt37vtf8RH+0g2qXA0vkTDouWiiTlOKl4iuqRmrb0CNM9lPPgGkCkPoyGurhpZ+8Tf3xW+NE/o=
  on:
    tags: true
    repo: yoctore/yocto-mongoose
before_install: npm install -g grunt-cli
install: npm install
services:
- mongodb
- elasticsearch
